name: Production Build and Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    build_sdist:
        name: Build SDist
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: true

            - name: Build SDist
              run: pipx run build --sdist

            - name: Check metadata
              run: pipx run twine check dist/*

            - uses: actions/upload-artifact@v7
              with:
                  name: cibw-sdist
                  path: dist/*.tar.gz

    build_wheels:
        name: Build wheels for ${{ matrix.python-version }}
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

        steps:
            - uses: actions/checkout@v6
              with:
                  submodules: true

            - uses: astral-sh/setup-uv@v7
            - uses: pypa/cibuildwheel@v3.4

            - name: Verify clean directory
              run: git diff --exit-code
              shell: bash

            - uses: actions/upload-artifact@v7
              with:
                  name: wheels-${{ matrix.python-version }}
                  path: wheelhouse/*.whl

    publish:
        name: Publish to PyPI
        needs: [build_sdist, build_wheels]
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write
            attestations: write
        steps:
            - name: Download Wheels
              uses: actions/download-artifact@v8
              with:
                  path: dist
                  pattern: wheels-*
                  merge-multiple: true

            - name: Generate artifact attestation for sdist and wheels
              uses: actions/attest-build-provenance@v4
              with:
                  subject-path: 'dist/*'

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
